# Generated by Django 5.2.5 on 2025-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
