# Generated by Django 5.2.5 on 2025-08-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_usersignup_userprofile_delete_authuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignUp',
            new_name='AuthUser',
        ),
    ]
