# Generated by Django 5.2.5 on 2025-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
